spring:
  application:
    name: co-write-be-kt
  profiles:
    active: dev

server:
  port: 8088
  servlet:
    context-path: /api

mybatis:
  type-aliases-package: io.github.hcisme.cowrite.entity.pojo,io.github.hcisme.cowrite.entity.query,io.github.hcisme.cowrite.entity.vo
  configuration:
    map-underscore-to-camel-case: true
